#!/usr/bin/env bash
set -exuo pipefail

export ROOT=/etc/opensprinkler

function get_required(){
    apt update -y
    apt upgrade -y

    apt install -y build-essential git

    rpi-update
}

function setup_user(){
    if ! id -u ospi; then
        useradd -G gpio -d ${ROOT} -s /bin/false ospi
    fi
    chown -R ospi:ospi ${ROOT}
}

function download_and_compile(){
    pushd /etc

    git clone https://github.com/stephen-mw/OpenSprinkler-Installer.git opensprinkler
    pushd opensprinkler

    git clone https://github.com/OpenSprinkler/OpenSprinkler-Firmware.git src

    pushd ${ROOT}/src
    ./build.sh ospi

    cp OpenSprinkler ../
    popd

    rm -rfv -- src

    pushd systemd
    cp ln -s $(pwd)/* /etc/systemd/
    popd
}

function cleanup(){
    chown -R ospi:ospi ${ROOT}
    systemctl demon-reload
    systemctl enable opensprinkler

    cat <<MESSAGE
OpenSprinkler is running on port 8080! The default password is "opendoor".

You may need to restart your computer depending on the updates that were installed.

The following commands might be useful to you:

# Check the logs:
sudo grep 'opensprinkler' /var/log/syslg

# Start, stop, restart the service
$ systemctl restart opensprinkler
$ systemctl start opensprinkler
$ systemctl stop opensprinkler

# To prevent opensprinkler from-autostarting in the future:
$ systemctl disable opensprinkler

Good luck!
MESSAGE
}

get_required
download_and_compile
setup_user
cleanup
