#!/usr/bin/env bash
set -exuo pipefail

export ROOT=/etc/opensprinkler

function get_required(){
    apt update -y
    apt upgrade -y

    apt install -y build-essential git ntp

    pip install RPi.GPIO

    rpi-update
}

function setup_user(){
    if ! id -u ospi; then
        useradd -G gpio -d ${ROOT} -s /bin/false ospi
    fi
    chown -R ospi:ospi ${ROOT}
}

function download_and_compile(){
    pushd /etc

    if [[ -d opensprinkler ]]; then
	rm -rfv opensprinkler
    fi
    git clone https://github.com/stephen-mw/OpenSprinkler-Installer.git opensprinkler
    pushd opensprinkler

    if [[ -d src ]]; then
	rm -rfv -- src
    fi
    git clone https://github.com/OpenSprinkler/OpenSprinkler-Firmware.git src

    pushd ${ROOT}/src
    ./build.sh ospi

    cp OpenSprinkler ../
    popd

    rm -rfv -- src

    ln -sf ${ROOT}/opensprinkler.service /etc/systemd/system/opensprinkler.service
}

function reset_script(){
    pushd ${ROOT}
    cat >> /etc/cron.d/reset_sprinkers <<CRON
@reboot root ${ROOT}/reset_sprinklers
CRON
}

function cleanup(){
    chown -R ospi:ospi ${ROOT}
    systemctl daemon-reload
    systemctl enable opensprinkler

    cat <<MESSAGE

#############################################################################
#
#                    Installation complete!
#
#############################################################################


OpenSprinkler is running on port 8080! The default password is "opendoor".

You may need to restart your computer depending on the updates that were installed.

The following commands might be useful to you:

Check the logs:

    sudo grep 'opensprinkler' /var/log/syslg

Start, stop, restart the service

    $ systemctl restart opensprinkler
    $ systemctl start opensprinkler
    $ systemctl stop opensprinkler

To prevent opensprinkler from auto-starting in the future:

    $ systemctl disable opensprinkler

Good luck!
MESSAGE
}

get_required
download_and_compile
setup_user
cleanup
