#!/usr/bin/env python

"Reset all of the sprinkler heads. Done every time the Raspberry Pi restarts"

import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)

PINS = [
    26, # 1
    19, # 2
    6,  # 3
    13, # 4
    5,  # 5
    20, # 6
    16, # 7
    21, # 8
]

try:
    for pin in PINS:
        GPIO.setup(pin, GPIO.OUT)
        GPIO.output(pin, GPIO.HIGH)
finally:
    GPIO.cleanup()
