#!/usr/bin/env python

import time

import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)

# These are the pins in the order they appear on the relay
PINS = [
        21, # 1
        16, # 2
        20, # 3
        5,  # 4
        13, # 5
        6,  # 6
        19, # 7
        26, # 8
        ]

def init():
    # This sets the pin mode to OUTPUT and HIGH on all pins. This will close the relay. We call this again at the end
    # end to make sure our relays are all closed if there's a failure
    for pin in PINS:
        GPIO.setup(pin, GPIO.OUT)
        GPIO.output(pin, GPIO.HIGH)

def switch():
    while True:
        for pin in PINS:
            print("Attempting pin %s" % pin)
            GPIO.output(pin, GPIO.LOW)
            time.sleep(0.5  )
            GPIO.output(pin, GPIO.HIGH)

try:
    init()
    switch()
finally:
    # Make sure all of the pins are properly closed and the relays off
    init()
    GPIO.cleanup()
